# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r-version }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r-version: 'release'}
          - {os: macOS-latest, r-version: 'release'}

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.config.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r-version }}
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rcmdcheck
            covr
            lintr
      - name: Check
        run: rcmdcheck::rcmdcheck(error_on = "error")
        shell: Rscript {0}
      - name: Coverage
        run: covr::codecov()
        shell: Rscript {0}
      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
